# Generated by Django 4.1.7 on 2023-04-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.TextField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('department', models.TextField(null=True)),
                ('material', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
